# Generated by Django 5.2.6 on 2025-09-05 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_catalogue_customerprofile_item_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='vendor_logos/'),
            preserve_default=False,
        ),
    ]
