# Generated by Django 5.2.6 on 2025-09-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_image_vendorprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
